
server:
  port: 1026


spring:
  application:
    name: TinyRealm


app:
  data:
    config-resource-path: classpath:config/resource/
    resource-path: classpath:config/resource/resource.json
    building-path: classpath:config/building/building.json