
server:
  port: 1026


spring:
  application:
    name: TinyRealm


app:
  data:
    config-resource-path: classpath:config/resource/
    ResourceType-path: classpath:config/resource/ResourceType.json