
server:
  port: 1026
  # 優化連接池配置
  tomcat:
    threads:
      max: 200
      min-spare: 10
    max-connections: 8192
    accept-count: 100
    connection-timeout: 20000

spring:
  application:
    name: TinyRealm
  
  # 啟用緩存
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=600s
  
  # 優化 Jackson 序列化
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
  
  # 優化文件上傳
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 應用程式自定義配置
app:
  data:
    storagePath: game_data/
    resource-path:        classpath:config/resource/resources.json
    building-path:        classpath:config/building/buildings.json
    terrain-path:         classpath:config/terrain/terrains.json
    map-path:             classpath:config/map/maps.json
    soldier-path:         classpath:config/soldier/soldiers.json
    item-path:            classpath:config/item/items.json
    enemies-path:         classpath:config/battle/enemies.json
  
  # 性能優化配置
  performance:
    # 啟動優化
    startup:
      async-loading: true
      parallel-loading: true
      lazy-loading: true
    
    # 緩存配置
    cache:
      enabled: true
      max-size: 1000
      ttl: 600
    
    # 並行處理
    concurrency:
      core-threads: 4
      max-threads: 8
      queue-capacity: 100