app:
  data:
    resource-types-path: classpath:static_data/resource_types.json
server:
  port: 1026


spring:
  application:
    name: TinyRealm
  
  kafka:
    bootstrap-servers : localhost:9092
    consumer:
      group-id: tiny-realm-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer




