
server:
  port: 1026


spring:
  application:
    name: TinyRealm


app:
  data:
    storagePath: game_data/
    resource-path:        classpath:config/resource/resources.json
    building-path:        classpath:config/building/buildings.json
    terrain-path:         classpath:config/terrain/terrains.json
    map-path:             classpath:config/map/maps.json
    soldier-path:         classpath:config/soldier/soldiers.json
    item-path:            classpath:config/item/items.json
    enemies-path:         classpath:config/enemies.json